version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_media: {}
  production_static: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: test_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: test_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    image: nginx
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - production_media:/app/ijara/media/
      - production_static:/app/staticfiles/
      - ./compose/production/nginx/:/etc/nginx/conf.d/
    depends_on:
      - django
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
