# Generated by Django 4.2.7 on 2023-11-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0002_announcement_transports_like_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="transports",
            field=models.ManyToManyField(related_name="announcements", to="announcement.transports"),
        ),
    ]
