# Generated by Django 4.2.7 on 2023-11-28 06:33

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(unique=True)),
                ("image", models.ImageField(upload_to=images.models.image_upload_path)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
