# Generated by Django 4.2.7 on 2023-11-29 12:02

from django.db import migrations, models
import test.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default=1,
                max_length=13,
                unique=True,
                validators=[test.users.models.validate_phone_number],
                verbose_name="Phone number",
            ),
            preserve_default=False,
        ),
    ]
